namespace SimpleRecorder.Contracts.Models;

public sealed record RecordingSessionTelemetry(
    string RequestedCaptureBackend,
    string CaptureBackend,
    string? CaptureFallbackFrom,
    string? CaptureFallbackTo,
    string CaptureFallbackReason,
    string? CaptureFallbackHresult,
    string EncodeBackend,
    bool IsHardwareEncode,
    string HardwareEncodeStatus,
    string EncoderPreference,
    string EncoderSelectionReason,
    string EncoderFallbackReason,
    string EncoderVendor,
    string EncoderName,
    string AdapterLuid,
    string VideoCodec,
    string EncoderPixelFormat,
    string GpuPipelineMode,
    int CaptureSlotCount,
    int CaptureQueueLimit,
    bool IsD3dMultithreadProtected,
    bool WasWgcStartupAttempted,
    double WgcFirstFrameLatencyMs,
    string? AdapterName,
    long CaptureAttempts,
    int RequestedFrameRate,
    int TargetFrameRate,
    double AverageFramesPerSecond,
    int OutputWidth,
    int OutputHeight,
    long CapturedFrames,
    long EncodedFrames,
    long DroppedFrames,
    long BackpressureDrops,
    long CaptureFailureDrops,
    long PacingOverruns,
    double AverageCaptureLatencyMs,
    double AverageQueueLatencyMs,
    double AverageConvertLatencyMs,
    double AverageEncodeLatencyMs,
    int PeakQueueDepth,
    string? FailureHresult,
    string QualityPresetName = "Unknown",
    long TargetBitrateBps = 0,
    long MaxBitrateBps = 0,
    string RateControlMode = "unknown",
    int QualityVsSpeed = 0,
    int GopSize = 0,
    bool IsCabacRequested = false,
    string EncoderConfigStatus = "unknown",
    string ColorPrimaries = "unknown",
    string TransferFunction = "unknown",
    string YuvMatrix = "unknown",
    string NominalRange = "unknown",
    string D3dInputColorSpace = "unknown",
    string D3dOutputColorSpace = "unknown");
