namespace SimpleRecorder.Contracts.Models;

public sealed record RecordingSessionTelemetry(
    string RequestedCaptureBackend,
    string CaptureBackend,
    string? CaptureFallbackFrom,
    string? CaptureFallbackTo,
    string CaptureFallbackReason,
    string? CaptureFallbackHresult,
    string EncodeBackend,
    bool IsHardwareEncode,
    string HardwareEncodeStatus,
    string EncoderPreference,
    string EncoderSelectionReason,
    string EncoderFallbackReason,
    string EncoderVendor,
    string EncoderName,
    string AdapterLuid,
    string VideoCodec,
    string EncoderPixelFormat,
    string GpuPipelineMode,
    int CaptureSlotCount,
    int CaptureQueueLimit,
    bool IsD3dMultithreadProtected,
    bool IsGpuHardwareDetected,
    bool IsCpuFallbackAllowed,
    bool IsCpuFallbackBlocked,
    string CpuFallbackBlockReason,
    string? GpuInitializationHresult,
    string CopyIntegrityStatus,
    long CopyDimensionMismatchCount,
    string? CopyIntegrityFailureReason,
    bool WasWgcStartupAttempted,
    double WgcFirstFrameLatencyMs,
    string? AdapterName,
    long CaptureAttempts,
    int RequestedFrameRate,
    bool IsMonitorFrameRateMode,
    int MonitorFrameRateLimit,
    int TargetFrameRate,
    double EffectiveFrameRate,
    int MonitorRefreshRate,
    bool WasMonitorFrameRateCapped,
    string FrameRatePolicy,
    string FpsCapReason,
    long DuplicatedFrames,
    double AverageFramesPerSecond,
    double WallDurationMs,
    double RepresentedDurationMs,
    double RepresentedToWallDurationRatio,
    int OutputWidth,
    int OutputHeight,
    long CapturedFrames,
    long EncodedFrames,
    long DroppedFrames,
    long BackpressureDrops,
    long CaptureFailureDrops,
    long PacingOverruns,
    double AverageCaptureLatencyMs,
    double AverageQueueLatencyMs,
    double AverageConvertLatencyMs,
    double AverageEncodeLatencyMs,
    int PeakQueueDepth,
    string? FailureReason,
    string? FailureHresult,
    string QualityPresetName = "Unknown",
    long TargetBitrateBps = 0,
    long MaxBitrateBps = 0,
    string RateControlMode = "unknown",
    int QualityVsSpeed = 0,
    int GopSize = 0,
    bool IsCabacRequested = false,
    string EncoderConfigStatus = "unknown",
    string ColorPrimaries = "unknown",
    string TransferFunction = "unknown",
    string YuvMatrix = "unknown",
    string NominalRange = "unknown",
    string D3dInputColorSpace = "unknown",
    string D3dOutputColorSpace = "unknown",
    int QualityPolicyVersion = 0,
    bool IsEncoderLowLatency = false,
    bool IsEncoderRealTime = false,
    bool IsEncoderFrameDropsAllowed = false,
    string EncoderFrameRateConversion = "unknown",
    string VideoProcessorUsage = "unknown",
    bool IsEdgeEnhancementRequested = false,
    bool IsEdgeEnhancementApplied = false,
    double CaptureFrameRate = 0,
    int EncodeContainerFrameRate = 0,
    double DuplicatedFrameRatio = 0,
    string H264Level = "unknown",
    int H264LevelValue = 0,
    string CropResizeMismatchReason = "none",
    long FirstSampleTimestampHns = 0,
    long LastSampleTimestampHns = 0,
    long LastSampleDurationHns = 0);
